Loading spinner and form loading handling
doskachok/magellan pull request #20
Opened 2022-08-08 20:56 UTC by AwesomeFlax

#18 
#10

2022-08-08 22:36 UTC, apximax requested changes

2022-08-08 22:36 UTC, apximax commented on src/components/Loader/index.tsx
> +    return (<></>);
```suggestion
    return null;
```

2022-08-11 16:09 UTC, AwesomeFlax commented on src/components/Loader/index.tsx
> +    return (<></>);
Done

2022-08-12 13:03 UTC, apximax approved these changes

2022-08-12 13:04 UTC, merged