Change div to button when it uses as button
doskachok/magellan pull request #71
Opened 2023-04-16 12:38 UTC by Gamgeee

2023-04-16 13:54 UTC, doskachok approved these changes, later dismissed
Nice!

2023-04-16 18:31 UTC, AwesomeFlax requested changes

2023-04-16 18:31 UTC, AwesomeFlax commented on src/features/expenses/AddExpense/MainInfo.styled.ts
> +import { ButtonTransparent } from "components/Button/index.styled";
I believe you forgot to register this button in general component import, that’s why you import comes from button. Please have a look how it’s done for the rest of texts and buttons and etc

2023-04-18 12:19 UTC, apximax approved these changes, later dismissed

2023-04-19 17:43 UTC, AwesomeFlax approved these changes

2023-04-20 18:21 UTC, merged